// Custom shader file for ns_frenzy.bsp
// Generated by Q3Map2 (ydnar)
// Do not edit! This file is overwritten on recompiles.

ns_frenzy/19F5D37DF6073CF12792AF747D12B3FC
{
	surfaceparm metalsteps
	{
		map textures/nsq3_metal/metalwall_0.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/nsq3_material/metal_shiny_03.tga
		blendfunc filter
		rgbGen identity
		tcGen environment
	}
}

ns_frenzy/F24A88682149CDF14BE967530C73D24E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_material/cement_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/76BD93CAD48FCE69E598E88E460551F4
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/golgatha_vehicle/vehlm113upperpanel1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/EAA62AB5D68034411358A189BF7B0CC2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/s8s/th_scraggywalldirty.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/0BB9A6E2778F0A0A96F3BC3C7D8CA45B
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/E9FCF1DB9F9915BC1D5D68E620838106
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0011.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/E7F20A28AA7DDDF61124307AE4F80192
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/06C347A64B2B3B081753617E1DB902A8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/chronic_trim/trim_aluminumpole.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/4CB2405029161683C7FF191972DBE4FE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/84D9C3310E1809EC01D66F87D9A400F9
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0012.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/3B442616CDD0DABBAA368CF96C8ED6BE
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_concrete/cement.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/3C6E7908C0324CD79391953C34343A21
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_6/decay1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/FA77B36CA6133A3AD91306ABC2B053DC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_6/decay1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/31431AC9CD446D1B5A0CF825CF037F43
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/s8s/th_scraggywall_burnt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/80D32C51F56DD702A321127E6B3BE2D0
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/masphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/AD38867FCC71A3CD69643CA206204709
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/graphtallica_8/crete33.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/91F689DE2C30E1B28A67FF4D422162D6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/crete33.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/B71B1D16DB1063AD62479310505F4120
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_misc/ladder_metal_04b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/5A211E52C1D2104F5880C78DBB636A46
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0010.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/89B193753EAEB19A4B346F01D7DE3865
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/F911CA53F3C42F0F70ED9794465BD937
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0013.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.00000 0.50000
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/3565B83F52223BD592519BE0331B89DC
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/crete28.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/0D9DEE43ECD82EE562E0D6526C0A305F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_9.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/1602A6B68C54B808FD280207A92FCF2D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0005.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_material/cement_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/FCCCBF505EB84386504272018A314816
{
	qer_editorimage textures/liquids/pool3d_3b.tga
	qer_trans .5
	q3map_globaltexture
	surfaceparm trans
	surfaceparm nonsolid
	surfaceparm water
	cull disable
	deformVertexes wave 64 sin .5 .5 0 .5
	{
		map textures/liquids/pool3d_5.tga
		blendFunc GL_dst_color GL_one
		rgbgen identity
		tcmod scale .5 .5
		tcmod transform 1.5 0 1.5 1 1 2
		tcmod scroll -.05 .001
	}
	{
		map textures/liquids/pool3d_6.tga
		blendFunc GL_dst_color GL_one
		rgbgen identity
		tcmod scale .5 .5
		tcmod transform 0 1.5 1 1.5 2 1
		tcmod scroll .025 -.001
	}
	{
		map textures/liquids/pool3d_3.tga
		blendFunc GL_dst_color GL_one
		rgbgen identity
		tcmod scale .25 .5
		tcmod scroll .001 .025
	}
	{
		map $lightmap
		blendFunc GL_dst_color GL_zero
		rgbgen identity
	}
}

ns_frenzy/B1DA17AD49446153A05AE3FE0AB694B0
{
	surfaceparm metalsteps
	{
		map textures/nsq3_material/metal_support_01.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/77BFE7C8368FFE343349345BADAB9CB8
{
	surfaceparm metalsteps
	{
		map textures/nsq3_material/metal_rust_08.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/EA383E8FC3BA30C1BB5873D07FC5C91B
{
	surfaceparm metalsteps
	{
		map textures/nsq3_material/metal_rust_04.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/C1653990FEB8870E552FDF0439697933
{
	surfaceparm metalsteps
	{
		map textures/nsq3_material/metal_rust_02.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/0A6281FF047866B94C5BFA57A16752A4
{
	surfaceparm metalsteps
	{
		map textures/nsq3_material/metal_rust_01.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/B95A0CC9CE501E8C7B031C9982C07D5F
{
	q3map_lightimage textures/chronic_metal/metal_fireescape.tga
	qer_trans .5
	surfaceparm alphashadow
	surfaceparm playerclip
	surfaceparm trans
	surfaceparm metalsteps
	cull none
	{
		map textures/chronic_metal/metal_fireescape.tga
		blendFunc GL_ONE GL_ZERO
		alphaFunc GE128
		depthWrite
		rgbGen identity
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
		depthFunc equal
	}
}

ns_frenzy/833C5F48F86F932D3B646F04C948C7DD
{
	surfaceparm metalsteps
	qer_editorimage textures/nsq3_material/metal_rust_08.tga
	{
		map textures/nsq3_material/metal_rust_08.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/DE8F8DE8FE8190DE7F50F5BD909A6804
{
	qer_editorimage textures/graphtallica_8/crete33.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/crete33.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/BB9D32ED839CA621C7879AE6D66D9354
{
	qer_editorimage textures/graphtallica_8/crete33.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/graphtallica_8/crete33.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/3E5C8803334F16C710720129D3DA4DB7
{
	qer_editorimage textures/nsq3_urban/concrete_13d.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13d.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/C488CEB9066FD2A9CFE33FE97C1F6404
{
	qer_editorimage textures/nsq3_urban/concrete_13c.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/D6BCA6CEEE54D1C7E31EBDD4F6A2F567
{
	qer_editorimage textures/nsq3_concrete/cement.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_concrete/cement.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/82FAF8606FD84DCD533B8AE1AE01700F
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.31250 0.00781
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/AA84916F0FC78400B19A8CCDA4AD43B2
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.03906 0.00000
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/E7609A4FCBDD7A5E57D844DD243CE350
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.52344 0.00781
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/A8FEAB0CD955E6E5D246D49816652C1C
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.35156 0.00000
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/1C32C0677809BA8007CC429A157D03D5
{
	surfaceparm metalsteps
	{
		map textures/nsq3_doors/gate1_320_256.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map textures/nsq3_material/metal_shiny_01.tga
		blendfunc filter
		rgbGen identity
		tcGen environment
	}
}

ns_frenzy/0212D519E24CEBBF1B4361F3EBEC551A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0007.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_material/cement_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/5986A83C7C0638D1241C56E1BD7C7D68
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0008.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_material/cement_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/4596DF464C6086806C42AA265E988958
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/golgatha_vehicle/vehlm113upperpanel1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/6FF7D742146B15BA55369C78BACBA581
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/s8s/th_scraggywalldirty.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/51E4B4C02D1094BF98BC32794E7FB9C5
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/AE002E182BB98AD3E0189444734D6405
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/485B47C1B923C4B1049B811C90E79A10
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/6E7065C745D277B5F4920039C4FA27AD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0002.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/chronic_trim/trim_aluminumpole.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/63B3C8382DA2CB051C141C9240CF05EA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/chronic_trim/trim_aluminumpole.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/A70A15D250A40842A7C4724387403BD2
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0000.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.50000 0.00000
	}

	{
		map textures/chronic_trim/trim_aluminumpole.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/972140DF3CA95D6AB88951538CFEA8E6
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/B65BB2C856B07CDCB92850783B65C7A1
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0016.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13d.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/3B2580086C768BE26D63023D7B616B30
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_concrete/cement.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/F89D9E58910F6BE5F8E614092DBE0693
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_6/decay1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/D8AE46A26D7B6D6EE76F8F6F059FAA7A
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0018.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/s8s/th_scraggywall_burnt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/43C769D00E09FBF73FB3A4A6300A620E
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/meat_trim/trim_rustygrove.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/D0F1DEC000FD85F87228EBBDDCB3EE3F
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0004.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/masphalt.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/97D5BC23D943D33AC9D13A543B8E9FAB
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/wall_11.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/2980B2C950091E562A491BBE6690D01D
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/crete33.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/5D5799DA7ACDB41F9A03C231321B1913
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.20313 0.15625
	}

	{
		map textures/nsq3_misc/ladder_metal_04b.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/69C11E49119C5200B513DFBC9A75DBD3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0017.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/D899F396250B65820F764E98796B0697
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/C0B5874BABE2BF533CBDEC9240DA21B8
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0015.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/F262C5AAE675B99BB4BC39EEF1E5F3D3
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0014.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/A10A47BF50D1C47A33C843711F22228C
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/crete28.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/7030ECF92E1FD28607B5DA3DF009DCBF
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_9.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/50E21CD0BECB7E81AD8654A7FEBEC4FA
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0006.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_material/cement_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/0645D42BECF9F0A60FC38E59C873B0AD
{ // Q3Map2 defaulted
	{
		map $lightmap
		rgbGen identity
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0009.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_material/cement_1.tga
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen identity
	}
}

ns_frenzy/66BF8CEF77A6576553A56FA7DBDD6AD9
{
	surfaceparm metalsteps
	qer_editorimage textures/golgatha_vehicle/vehltopfrnt2sml.tga
	{
		map textures/golgatha_vehicle/vehltopfrnt2sml.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/B27B100282DFA73E857AD4342431C009
{
	surfaceparm metalsteps
	qer_editorimage textures/golgatha_vehicle/vehlm113upperpanel1.tga
	{
		map textures/golgatha_vehicle/vehlm113upperpanel1.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/0F405C7E50223E85FC6603FA2BB8F764
{
	surfaceparm metalsteps
	qer_editorimage textures/golgatha_vehicle/vehlm113tri2.tga
	{
		map textures/golgatha_vehicle/vehlm113tri2.tga
	}
	{
		map $lightmap
		rgbGen identity
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/CACB2D03AEB8ED434D9CBA19CBC21454
{
	qer_editorimage textures/graphtallica_8/crete33.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/graphtallica_8/crete33.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/7F709E3C58FCB5B6F96259928F365458
{
	qer_editorimage textures/nsq3_urban/concrete_13d.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13d.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/E080D9735333EFD11F718B366339B9F8
{
	qer_editorimage textures/nsq3_urban/concrete_13c.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0003.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_urban/concrete_13c.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/DB2E8EC91E14858A2299703B412DA2E9
{
	qer_editorimage textures/nsq3_concrete/cement.tga
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map maps/ns_frenzy/lm_0001.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
	}

	{
		map textures/nsq3_concrete/cement.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/D92F4AF60639F618BC18BAE9A03438C7
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.50000 0.50000
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/79C7055016017AD27E08E42C005F32F8
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.13281 0.00000
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/F9584B01779D0E9BC736BE385E7B47BF
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 0.53906 0.00000
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

ns_frenzy/69F12742DF64229E77C1DBDA719133A1
{
	qer_editorimage textures/nsq3_misc/light_05.tga
	q3map_lightStyle 1
	surfaceParm noMarks
	q3map_surfaceLight 30000
	{
		map $lightmap
	}
	
	// Q3Map2 custom lightstyle stage(s)
	{
		map $lightmap
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave square .5 1 .25 1.28 // style 1
		alphaGen wave square .5 1 0 .37 // style 1
		tcGen lightmap
		tcMod transform 1 0 0 1 -0.94531 0.00781
	}

	{
		map textures/nsq3_misc/light_05.tga
		blendFunc GL_DST_COLOR GL_ZERO
	}
}

